image: docker:20.10.9

pipelines:
  branches:
    main:
      - step:
          name: Rubocop
          image: ruby:3.1.0
          script:
            - gem install bundler
            - gem install rubocop rubocop-rails
            - rubocop
      - step:
          name: Build and Push Docker Image
          services:
            - docker
          script:
            - export DOCKER_BUILDKIT=1
            - docker build -t naveediftikhar/readinglab:latest .
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker push naveediftikhar/readinglab:latest
      - step:
          name: Deploy to DigitalOcean
          deployment: Readinglab
          trigger: manual
          script:
            - pipe: atlassian/ssh-run:0.4.3
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER
                MODE: 'script'
                COMMAND: 'deploy.sh'
