image: docker:20.10.9

pipelines:
  default:
    - step:
        name: Rubocop
        image: ruby:3.1.0
        script:
          - gem install bundler
          - gem install rubocop rubocop-rails
          - rubocop
    - step:
        name: Build and Push Docker Image
        services:
          - docker
        script:
          - chmod -R 644 ./*
          - docker build -t naveediftikhar/readinglab:latest .
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker push naveediftikhar/readinglab:latest
