version: '3.8'

x-app: &default-app
  build:
    context: .
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
      - "RAILS_ENV=${RAILS_ENV:-production}"
      - "NODE_ENV=${NODE_ENV:-production}"

  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - "${DOCKER_WEB_VOLUME:-./public:/app/public}"

services:
  worker:
    <<: *default-app
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    entrypoint: []
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WORKER_CPUS:-0}"
          memory: "${DOCKER_WORKER_MEMORY:-0}"

  web:
    <<: *default-app
    deploy:
      # replicas: 2
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:3000/health}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - '${DOCKER_WEB_PORT_FORWARD:-3000}:${PORT:-3000}'
    depends_on:
      - "worker"

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      SOME_ENV: some_data
    volumes:
      - ./readinglab.nginx.conf:/etc/nginx/conf.d/readinglab.conf
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - "web"
      # - "certbot"

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt:rw
  #     - ./certbot/www:/var/www/certbot:rw
  #   depends_on:
  #     - nginx
  #   # command: certonly --webroot -w /var/www/certbot/ --force-renewal --email saad@gmail.com -d saaad.local.com --agree-tos
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot:/var/www/certbot
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   command: certonly --webroot --webroot-path=${CERTBOT_PATH:-/var/www/certbot} --email saad@gmail.com --agree-tos -d saaad.local.com --staging


    # environment:
    #   PORT: ${PORT}
    #   RAILS_ENV: ${RAILS_ENV}
    #   NODE_ENV: ${NODE_ENV}
    #   DEFAULT_MERGE_PASSWORD: ${DEFAULT_MERGE_PASSWORD}
    #   REDIS_URL: ${REDIS_URL}
    #   DB_NAME: ${DB_NAME}
    #   DB_USER: ${DB_USER}
    #   DB_PASS: ${DB_PASS}
    #   DB_HOST: ${DB_HOST}
    #   DB_PORT: ${DB_PORT}
    #   SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    #   WEB_CONCURRENCY: ${WEB_CONCURRENCY}
    #   RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
    #   DOCKER_WEB_VOLUME: ${DOCKER_WEB_VOLUME}
      # DOCKER_RESTART_POLICY: ${DOCKER_RESTART_POLICY}
