default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV.fetch("DB_NAME") { "readinglab" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASS") { "postgres" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: "<%= ENV.fetch("DB_POLL") { 5 } %>"
  statement_limit: 200

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
