default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV.fetch("DB_NAME") { "readinglab" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASS") { "postgres" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: "<%= ENV.fetch("DB_POLL") { 5 } %>"
  statement_limit: 200

development:
  primary:
    adapter: postgresql
    encoding: utf8
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USER'] %>
    password: <%= ENV['DB_PASS'] %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    statement_limit: 200

  old_readinglab:
    adapter: postgresql
    encoding: utf8
    database: <%= ENV['OLD_DB_NAME'] %>
    username: <%= ENV['OLD_DB_USER'] %>
    password: <%= ENV['OLD_DB_PASS'] %>
    host: <%= ENV['OLD_DB_HOST'] %>
    port: <%= ENV['OLD_DB_PORT'] %>
    statement_limit: 200

test:
  <<: *default

production:
  <<: *default
