---

:queues:
  - default
  - mailers
:scheduler:
  :schedule:
    archive_klasses:
      cron: '0 0 * * *'   # Runs at midnight (00:00) every day
      class: ArchiveKlassesJob
    delete_seen_notifications:
      cron: '0 0 * * *'   # # Runs at midnight (00:00) every day
      class: DeleteNotificationsJob
    # process_billing:
    #   cron: '0 0 1 * *'   # Runs once per month
    #   class: ProcessAllStudentJob
    process_daily_student_billing_job:
      cron: '0 8 * * *'
      class: ProcessDailyStudentBillingJob
    Class_Extend_Notification_Job:
       cron: '0 0 * * 1'  # Runs once per week (00:00) monday
       class: ClassExtendNotificationJob
    attendance_reminder:
      cron: '0 0 * * *'   # Runs at midnight (00:00) every day
      class: AttendanceReminderJob
