apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: webapp
        image: naveediftikhar/readinglab:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DB_NAME
            value: readinglab_prod
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-host
          - name: DB_PORT
            value: '5432'
          - name: SECRET_KEY_BASE
            value: '123456789'
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
