apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  # DB_NAME: cmVhZGluZ2xhYl9wcm9k
  # DB_USER: cG9zdGdyZXM=
  # DB_PASS: cG9zdGdyZXM=
  # # DB_HOST: MTI3LjAuMC4x
  # DB_HOST: aG9zdC5kb2NrZXIuaW50ZXJuYWw=
  # DB_PORT: NjU0MzI=
